### ISSUE TITLE
SSL/Connection error connecting to GitHub

### ISSUE THREAD

**Issue by JoetheInkling** [solsticegamestudios/GModPatchTool#139]
I got GMOD recently, and I tried this out so it'll work for me but then I got some sort of error, I seriously need help:

Traceback (most recent call last):
  File "GModCEFCodecFix.py", line 638, in <module>
  File "httpx/_api.py", line 210, in get
  File "httpx/_api.py", line 118, in request
  File "httpx/_client.py", line 837, in request
  File "httpx/_client.py", line 926, in send
  File "httpx/_client.py", line 954, in _send_handling_auth
  File "httpx/_client.py", line 991, in _send_handling_redirects
  File "httpx/_client.py", line 1027, in _send_single_request
  File "httpx/_transports/default.py", line 235, in handle_request
  File "contextlib.py", line 155, in __exit__
  File "httpx/_transports/default.py", line 89, in map_httpcore_exceptions
httpx.ConnectError: EOF occurred in violation of protocol (_ssl.c:1002)

**Comment by WinterPhoenix** [comment]
Your antivirus, internet service provider, or government is breaking it.

If it's one of the latter two, using a VPN like [ProtonVPN](https://protonvpn.com/) will fix it.

**Comment by JoetheInkling** [comment]
> Your antivirus, internet service provider, or government is breaking it.
> 
> If it's one of the latter two, using a VPN like [ProtonVPN](https://protonvpn.com/) will fix it.

But then it'll cost me money. Is there any other alterbative way to prevent them from breaking it?

**Comment by WinterPhoenix** [comment]
ProtonVPN is both free and not sketchy. It's probably the only VPN in the world that can claim that.

**Comment by RiQuY** [comment]
I'm getting the same error on openSUSE Tumbleweed (Linux), I have no antivirus and I'm pretty sure my government is not blocking the connection because it fails after downloading several files.

System info:
- openssl version: 3.2.3-1.1
- OS: openSUSE Tumbleweed
- Kernel version: 6.12.6-1-default
- DE: KDE Plasma 6.2.4
- WM: KWin (Wayland)
- CPU: AMD Ryzen 7 1700X (16) @ 3.40 GHz
- GPU: AMD Radeon RX 5700 XT [Discrete]
- RAM: 32GB

Full log:
- https://gist.github.com/RiQuY/4032891568646c76ad3008259fa6f223

**Comment by WinterPhoenix** [comment]
The new Rust rewrite of the tool now uses our web server as a backup to get patch files in the case that your connection to GitHub fails:
https://github.com/solsticegamestudios/GModPatchTool/releases
